In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


# NUMPY

In [2]:
import numpy as np

arr = np.array([4,7,8,9])
print(type(arr))

<class 'numpy.ndarray'>


In [3]:
print(arr)

[4 7 8 9]


In [4]:
print(arr[3])

9


In [5]:
print(arr[-2])

8


In [7]:
print(arr[0:4])

[4 7 8 9]


In [8]:
print(arr[0:4:2])

[4 8]


In [10]:
print(arr[-1:-4:-1])

[9 8 7]


In [11]:
print(arr.ndim)

1


In [13]:
arr = np.array(4)
print(arr.ndim)

0


In [19]:
arr = np.array([[[4,7,8],[2,3,5]]])

In [20]:
print(arr.ndim)

3


In [21]:
print(arr)

[[[4 7 8]
  [2 3 5]]]


In [24]:
arr = np.array([4,7,8], ndmin = 5)

In [25]:
print(arr.ndim)

5


In [26]:
print(arr)

[[[[[4 7 8]]]]]


In [27]:
arr = np.array([4,7,8,9])

print(arr.dtype)

int64


In [28]:
arr = np.array([4,7,8,9], dtype = "i")

print(arr.dtype)

int32


In [29]:
arr = np.array([4,7,8,9, 11,23, 6], dtype = "f")

In [30]:
print(arr.dtype)

float32


In [31]:
print(arr)

[4. 7. 8. 9.]


In [33]:
print(arr.astype('i'))
print(arr)

[4 7 8 9]
[4. 7. 8. 9.]


In [35]:
arr = np.array([[4,7,8],[4,7,9]])
print(arr[0,1])

7


In [36]:
print(arr[1,1])

7


In [37]:
print(arr[1,2])

9


In [39]:
print(arr[0:2,0:2])

[[4 7]
 [4 7]]


In [46]:
arr = np.array([[4,5,6],[7,8,9]])
print(arr[0:2,-1:-4:-1])

[[6 5 4]
 [9 8 7]]


In [47]:
import os
os.getcwd()

'C:\\Users\\alire\\Data Science Course - 55H'

## Numpy - part 2

In [7]:
import numpy as np

arr= np.array([[4,6,7],[3,21,11]])

In [8]:
print(arr.shape)

(2, 3)


In [10]:
arr= np.array([4,6,11,5,6,9])

In [11]:
print(arr.reshape((2,3),))

[[ 4  6 11]
 [ 5  6  9]]


In [13]:
print(arr.reshape((2,4),))

ValueError: cannot reshape array of size 6 into shape (2,4)

In [14]:
print(arr.reshape((3,2),))

[[ 4  6]
 [11  5]
 [ 6  9]]


In [18]:
data = [34, 46565, 346566, 67878, 8989900]

with open('1.csv', 'w') as f:
    f.write(','.join(map(str, data)))

In [15]:
arr= np.array([4,6,11,5,6,9,1,45])

In [16]:
print(arr.reshape((2,2,2),))

[[[ 4  6]
  [11  5]]

 [[ 6  9]
  [ 1 45]]]


In [ ]:
data = [34, 46565, 346566, 67878, 8989900]

with open('1.csv', 'w') as f:
    f.write(','.join(map(str, data)))

In [25]:
# change data type from string to int
f = open("1.csv", "r")

list = f.read().split(",")

arr = np.asarray(list)
print(type(arr))
    
    

<class 'numpy.ndarray'>


In [26]:
print(arr)

['34' '46565' '346566' '67878' '8989900']


In [28]:
# change data type from str to int

arr = np.asarray(list, "i")
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[     34   46565  346566   67878 8989900]


In [29]:
# give us number of elemet
print(arr.shape)


(5,)


In [31]:
print(np.amin(arr))

34


In [32]:
print(np.amax(arr))

8989900


In [33]:
print(np.mean(arr))

1890188.6


In [34]:
print(np.median(arr))

67878.0


In [35]:
import numpy as np
arr = np.array([2,3,4,5])

for x in arr:
    print(x)

2
3
4
5


In [39]:
arr = np.array([[2,3],[4,5]])

for x in arr:
    for i in x:
        print(i)

2
3
4
5


In [43]:
arr = np.array([[[2,3],[4,5],[6,7]]])

for x in np.nditer(arr):
    print(x)

2
3
4
5
6
7


In [45]:
arr = np.array([2,3, 5, 8],ndmin = 5)

for x in np.nditer(arr):
    print(x)

2
3
5
8


### multiply matrices

In [50]:
arr1 = np.array([[2,3],[5, 8]])

arr2 = np.array([[4,6],[2,8]])

print(np.multiply(arr1,arr2))

[[ 8 18]
 [10 64]]
